site_name: banco-quarkus-app
site_description: Servicio de banco
repo_url: https://gitlab-gitlab.apps.cluster-5264f.5264f.sandbox1905.opentlc.com/development/banco-quarkus-app
edit_uri: edit/master/docs

plugins:
  - techdocs-core

# Note for content editors, edit only the section below
nav:
  - Onboard a developer to OpenShift: onboard-openshift.md
  - Application Migration:
      - Migration Process Overview: application-migration/migration-process-overview.md
      - Migration Process Steps: application-migration/migration-process-steps.md
      - Learning Path for Developers: application-migration/learning-path-for-developers.md
